//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCT.GUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSCT.GUI.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        internal static string AnErrorOccured {
            get {
                return ResourceManager.GetString("AnErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ChannelIsConnected {
            get {
                return ResourceManager.GetString("ChannelIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string ChannelIsDisconnected {
            get {
                return ResourceManager.GetString("ChannelIsDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Established.
        /// </summary>
        internal static string ContextIsEstablish {
            get {
                return ResourceManager.GetString("ContextIsEstablish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        internal static string ContextIsReleased {
            get {
                return ResourceManager.GetString("ContextIsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s) occured when accessing layer &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorAccessingLayerAssemblyX {
            get {
                return ResourceManager.GetString("ErrorAccessingLayerAssemblyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s) occured when accessing plugin &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorAccessingPluginAssemblyX {
            get {
                return ResourceManager.GetString("ErrorAccessingPluginAssemblyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s) occured when launching plugin &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorWhenLaunchingPluginX {
            get {
                return ResourceManager.GetString("ErrorWhenLaunchingPluginX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Error: {0}.
        /// </summary>
        internal static string LastErrorIsX {
            get {
                return ResourceManager.GetString("LastErrorIsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader groups descriptionFound: {0}.
        /// </summary>
        internal static string ReaderGroupsFoundAre {
            get {
                return ResourceManager.GetString("ReaderGroupsFoundAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readers descriptionFound: {0}.
        /// </summary>
        internal static string ReadersFoundAre {
            get {
                return ResourceManager.GetString("ReadersFoundAre", resourceCulture);
            }
        }
    }
}
